name: CI

on: [push, pull_request]

jobs:
  build_wii_raw:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find _ark/songs/ -name "*.dta" -type f -delete
          find _ark/songs/updates/ -name "*.mid" -type f -delete
          find _ark/songs/updates/ -name "*.png" -type f -delete
          find _ark/songs/updates/ -name "*.milo_wii" -type f -delete
          find _ark/songs/updates/ -empty -type d -delete
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_xbox" -type f -delete
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/wii/gen -n "patch_wii" -e -v 6
          dependencies/arkhelper ark2dir ./_build/wii/gen/patch_wii.hdr ./_build/wii/rawfiles -a
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-Wii-Rawfiles
          path: _build/wii/rawfiles
